# Step 1: Build Stage
FROM node:current-slim AS build
WORKDIR /app

# Copy package files first to leverage Docker cache
COPY package*.json ./

# Install all dependencies (including devDeps like nuxt for building)
RUN npm install

# Copy the rest of the source code
COPY . .

# Build the Nuxt application
RUN npm run build

# Step 2: Production Stage
FROM node:current-slim AS production
WORKDIR /app

# Only copy the essential .output directory generated by Nuxt
COPY --from=build /app/.output /app/.output

# Nuxt/Nitro server configuration
ENV PORT=3000
ENV NODE_ENV=production

EXPOSE 3000

# Start using the standalone Nitro server
CMD ["node", ".output/server/index.mjs"]
